# Dockerfile.backend
FROM node:20

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./

RUN npm install

COPY backend/ ./

RUN npx prisma generate

EXPOSE 4000

# Start server
CMD ["npm", "run", "dev"]