FROM node:20

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./

RUN npm install

COPY backend/ ./

#  Accept the variable from GitHub Actions 
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
# ---------------------------------------------------

RUN npx prisma generate

EXPOSE 4000

# Start server
CMD ["npm", "run", "dev"]